### ISSUE TITLE
Expore LDP Graphs

### ISSUE THREAD

**Issue by vemonet** [MaastrichtU-IDS/into-the-graph#25]
Virtuoso LDP generates a lots of graphs

See http://trek.semanticscience.org/describe?uri=http://w3id.org/FAIR_Training_LDP/DAV/home/LDP/Training/Murcia/marks_resource.ttl&endpoint=http://w3id.org/FAIR_COVID19/sparql/

A good way to navigate LDP for this use-case:

```
PREFIX ldp: <http://www.w3.org/ns/ldp#> 
PREFIX schema: <http://schema.org/> 
SELECT ?crateContainer WHERE { 
  GRAPH ?crateContainer { 
    ?crateContainer ldp:contains ?crate .
  } 
  GRAPH ?crate { ?s schema:studyDesign "Cohort" .} 
}
```

Should we have a switch to allow to get all triples in graphs instead of just classes?

**Comment by micheldumontier** [comment]
good idea!

**Comment by vemonet** [comment]
Added in https://github.com/MaastrichtU-IDS/into-the-graph/commit/198a44f4bb77e9c6521472984abff281d578e5a0 

http://trek.semanticscience.org/ updated 

A dropdown is now available in the [settings page](http://trek.semanticscience.org/settings) to choose the type of graph URI resolution:
* Only classes (still need to be improved, maybe by adding a distinct, but this can slow the query down a lot to the point of crashing in big graphs)
* Show all triples in the graph (limit 1000)

Showing all triples in the graph is working well for small graphs (nanopubs, LDP), but will miss a lot of infos in big graphs

The integration in the UI is not completly finished (it needs some refactorisation to properly pack by subject URI), but it works fine on FAIR_COVID19 for example
